[general]
app_name = "Point in Time Count Tool"
organization = "Institute for Community Alliances"
version = "2.0.0"
environment = "development"

# User credentials (use hashed passwords in production)
[users]
admin = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"  # SHA-256 hash of 'admin'
demo = "2a97516c354b68848cdbd8f54a226a0a55b21ed138e207ad6c5cbb9c00aa5aea"  # SHA-256 hash of 'demo'
user = "04f8996da763b7a969b1028ee3007569eaf3a635486ddab211d512c85b9df8fb"  # SHA-256 hash of 'user'

# Region-specific configurations
[regions]
default = "New England"
available = ["New England", "Dashgreatlake"]


# Feature flags
[features]
enable_dashboard = true
enable_advanced_filters = true
enable_export = true
enable_user_management = false